version: "1.0"

services:
  app:
    build:
      context: ./nodejs2024Q1-service
    ports:
      - "3000:3000"
    networks:
      - my-bridge

  db:
    image:
    networks:
      - my-bridge

networks:
  my-bridge:
    driver: bridge
    name: my-bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.50.0/24