version: "1.0"

services:
  web:
    image: my-web-app:latest
    ports:
      - "80:80"
    volumes:
      - ./app-data:/var/www/html
    environment:
      - DATABASE_URL=db:3306
      
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql